#! /bin/bash
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZZ05KY5J*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVVN1L8JD3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKV1CFR99*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAKLPG0GB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVGCDY2UAK*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVA940A4NE*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0AUBJJJ4*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6CZ8A7P2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3F2UEE7D*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVL5KEXX4Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZVW3HKWN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKHDHWB2T*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVLABWKL63*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7MR18DLV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVFV0NBDHW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMMZP7T96*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVY19N2XDD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVA7CLY4PL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV33FEYMMB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV20CZ5PTX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDWJKX2YR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVP9NTMNTN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV56KML05T*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVM2JLZJJ1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVF71CL4P2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNFWYZZJR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKNHT54VZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV14AFR5D4*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVY064R00W*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNBU3UA23*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMUG529LW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVFM186DJL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNGAXVYPV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5V1FEEAW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4W3GW9WL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV1TFVYFMB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYUPPEV2G*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV9H4U1DHY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZU422XFY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVED51W527*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV84EPJRY1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVENKLYX1L*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVHBGX2W56*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVE4NE0L80*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVPCV7FMWH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJGFBY8J1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCBVP6BDH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV55HCZHHV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVRREA9RBW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWW5E3PXX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVD76PJ8X7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVH2Z1AXE3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZW88GN71*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVK36E1PEB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVU697JENW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVBWT96BWH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVY51F4FMX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVC4EAMHZ7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWVFZTJX6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMAXZDNVW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVH2CGXAAN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVP7PFH5GK*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVB68067CD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVXNVL1783*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5FUBUX54*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVBLYFK2HJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV36TXKJEW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZ6FGXNPH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV93WX6071*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3UUD5J8C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVL1GA12Y1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVA7PB1MWM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVL124KUNM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYXMFACD7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6CNL0TLZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYH8W7XH2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZ5BHJRP7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMKWH6RED*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVRL1GM16T*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6E7NETJT*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVF6BJCNW6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVPB7TWVGE*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTY5H5PHZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWK84XHKV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVHAD1KFV7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVGV5N5P10*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0YGRZTUF*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVG91T2JF8*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVT9E1CUGM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVT1C2GBHB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNZ2C50P3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV62VXCMPT*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVB7PW7GZA*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV2XGC3LN5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6PK3TH3F*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVF4G76BRL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKV9CRFTM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCL18941F*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV1KAEAHY9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4XEMVP0N*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVX40BPRMT*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV91BAHLL2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVBKW33JVR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVV5Y81HT9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV91P92GNW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV1CV6NNKT*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVY9DCYBXW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVXNKDAEH6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVUCXEZB27*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVY0YM6R2T*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDU50FZ05*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVXLYDYTLX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVXGPKHPUV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVG2RXUFF1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZZZP87KR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYRRPGLF4*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAH92KG8X*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVV1UUN23J*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYT2MVJEZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVA9H3WMHD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVFCVZ66WZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWT60P58U*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVW3FWG7L0*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMYUP1YJ7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCKA8AFM8*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVMN7K3JN0*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVEY3GRANZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVHLKBLZ33*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDLXJMXAG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5DJB8FFX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAZ2THFRK*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVHXHUVGJG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTM4YT5UD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV747ZXA8Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVFJVMZ2D6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTFRBC95E*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVW7YX6WG3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCKDU4DXE*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVN0JV7RUL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3RTWYZX5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVW1EJC2L6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7E36P23G*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVU9H7T90F*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZ6950R7M*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6RWCZUXZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV1XKLCFDR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV38BUHW31*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV97A3711A*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNKBLG2AL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7XER6781*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV8P62FV1D*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVR7WBBFTB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDE17JJG5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVW8W3GAH9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVP5J0UJXG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZJD4XU1U*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7GCR03MF*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVB15ECXNF*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6DYLLUU6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5UJ10BMU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZ730VLUZ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV1TP6LCDF*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNF2BWTVU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZ5G203VB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7YFTLJBG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVN1HATRZN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVM8HMUPN5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVFRW3A0M2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCPYE49R9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVD32LCBUY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTABF5AC1*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4Z38T1RY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDBF7Z5CL*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5UJ0L2AV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKVMU7J2K*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV88V8C4GJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJLXMB8LP*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVC0BDYBKD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3RFU7ZRP*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAN0BA3ZM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVDHJNAJ5Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCCL8MNW4*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNW8TFAV3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4RX5LRX2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVRFGCXLTN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYBC941EU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVBK3K7AN8*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTZ5XBL2L*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV8P7ZETEX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVM15U5KMV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAZ3DJH9K*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYK2J75TH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7LNN715D*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0J2UAG61*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVM8LL41UF*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAWG2NZC4*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVPFC26GTC*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJGJVLK16*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVTEB0VDTW*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWM0HJKFC*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJ2CBCRYX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVW5T73BJ9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0AZFZ65C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYJ7PYHV7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKPLUBC73*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV5VP4RK9P*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV9Y43MGV3*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVC9N11UXX*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAX2MYFH9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVG4HBU1Y0*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVNC2BCXWR*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3YJA47GG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVKFZM65LP*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0AU5R8NA*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVEL7GGP0Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4P9B9PGN*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVWB0RVAGY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV233UX0N5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVVCAHYYKD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV4BRAVBYU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYKPWRXF2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVYW440F27*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVZWP490TG*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVHPVL425U*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVLEXJMGJ6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6MB1G78W*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVF1B8U3G5*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCPAB62JD*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV8JFP0XXH*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV6LNW0KV6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3YVFTTE6*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVR7E6XG5K*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVML1A2JFY*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJ1XKYGP9*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVG2ZHGAWM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVJ22VD7L7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV7LWNRC3F*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV0YLJKU2J*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVAU7FW44R*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV04BFG4JM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVR6FAP3A7*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVEJHM574R*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINVCLAFAT0D*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV8MXA9EYV*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV3BVCVP02*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV005V6D2C*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV007W6H7B*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00CY2MDM*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00HEV6HB*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LH735Y*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00LJVZK2*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00NPMHND*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00R4TXET*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00U4FTRU*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
rsync -achR /data/MBDU/ABCDraw/./*/NDARINV00X2TBWJ*.tgz abcdqc_backend_user:/abcdqc_data/ABCDraw/
